In [66]:
# from pykrx import stock
import matplotlib.pyplot as plt
import FinanceDataReader as fdr
import pandas as pd
import numpy as np
import scipy.stats as stats

# ticker = "012030"

# t_name = stock.get_market_ticker_name(ticker)

# a = stock.get_market_ohlcv("20220720", "20220810", ticker)

In [13]:
df_krx = fdr.StockListing('KRX').filter(["Symbol","Market","Name"])

In [14]:
df_krx

      Symbol  Market                     Name
0     060310  KOSDAQ                       3S
1     105190   KOSPI                  ACE 200
2     332500   KOSPI                ACE 200TR
3     448870   KOSPI  ACE 23-12 회사채(AA-이상)액티브
4     448880   KOSPI  ACE 24-12 회사채(AA-이상)액티브
...      ...     ...                      ...
7017  437550   KOSPI         히어로즈 글로벌리츠이지스액티브
7018  419890   KOSPI          히어로즈 단기채권ESG액티브
7019  429870   KOSPI            히어로즈 리츠이지스액티브
7020  454780   KOSPI      히어로즈 종합채권(AA-이상)액티브
7021  238490  KOSDAQ                       힘스

[7022 rows x 3 columns]

In [105]:
stock = fdr.DataReader(stockCode[0],startDate,endDate).filter(['Close','Change'])
print(stock['Change'].var())

0.0010043166918315067

In [95]:
startDate = '2022-06-01'
endDate = '2023-01-01'

stockCode = ['016380','004690']

n=len(stockCode)

# cnt = [20,30,50]

cnt = [40, 60]

# w1 = 0.2
# w2 = 0.3
# w3 = 0.5

In [99]:
start_price = []
end_price = []
start_value = []
end_value = []
ugl = []
return_rate = []
avg_change = []
var_change = []

total_start_value = 0
total_end_value = 0

for i in range(n):
    stock = fdr.DataReader(stockCode[i],startDate,endDate).filter(['Close','Change'])
    
    start_price.append(stock['Close'][0])
    end_price.append(stock['Close'][-1])
    start_value.append(start_price[i] * cnt1)
    end_value.append(end_price[i] * cnt1)
    ugl.append(end_value[i] - start_value[i])
    return_rate.append(ugl[i] / start_value[i])
    avg_change.append(stock['Change'].mean())
    var_change.append(stock['Change'].var())
    total_start_value += start_value[i]
    total_end_value += end_value[i]

total_ugl = total_end_value - total_start_value
total_rr = total_ugl / total_start_value
    
pf_err = 0

for i in range(n):
    w = cnt[i] / sum(cnt)
    pf_err += (w * avg_change[i])

pf_VAR = 0  

for i in range(n):
    for j in range(n):
        stock_i = fdr.DataReader(stockCode[i],startDate,endDate).filter(['Close','Change'])
        stock_j = fdr.DataReader(stockCode[j],startDate,endDate).filter(['Close','Change'])
        w_i = cnt[i] / sum(cnt)
        w_j = cnt[j] / sum(cnt)
#         v = w_i * w_j * np.sqrt(var_change[i]) * np.sqrt(var_change[j]) *  stats.pearsonr(stock_i['Change'],stock_j['Change'])[0]
        print(w_i, w_j,np.sqrt(var_change[i]),np.sqrt(var_change[j]),stats.pearsonr(stock_i['Change'],stock_j['Change'])[0])
        pf_VAR += (w_i * w_j * np.sqrt(var_change[i]) * np.sqrt(var_change[j]) *  stats.pearsonr(stock_i['Change'],stock_j['Change'])[0])

print(total_start_value, total_end_value, total_ugl, total_rr)
print(pf_err, pf_VAR)
# stock1_start_price = stock1['Close'][0]
# stock1_end_price = stock1['Close'][-1]
# stock1_start_value = stock1_start_price * cnt1
# stock1_end_value = stock1_end_price * cnt1
# stock1_ugl = end_value - start_value
# stock1_rr = stock1_ugl / stock1_start_value

# stock2_start_price = stock2['Close'][0]
# stock2_end_price = stock2['Close'][-1]
# stock2_start_value = stock2_start_price * cnt2
# stock2_end_value = stock2_end_price * cnt2
# stock2_ugl = end_value - start_value
# stock2_rr = stock2_ugl / stock2_start_value

# stock3_start_price = stock3['Close'][0]
# stock3_end_price = stock3['Close'][-1]
# stock3_start_value = stock3_start_price * cnt3
# stock3_end_value = stock3_end_price * cnt1
# stock3_ugl = end_value - start_value
# stock3_rr = stock3_ugl / stock3_start_value

# stock1_avg_change = stock1['Change'].mean()
# stock2_avg_change = stock2['Change'].mean()
# stock3_avg_change = stock3['Change'].mean()

# stock1_var_change = stock1['Change'].var()
# stock2_var_change = stock2['Change'].var()
# stock3_var_change = stock3['Change'].var()

0.4 0.4 0.031690955994281816 0.031690955994281816 1.0
0.4 0.6 0.031690955994281816 0.021572909169017097 0.19126537798186954
0.6 0.4 0.021572909169017097 0.031690955994281816 0.19126537798186954
0.6 0.6 0.021572909169017097 0.021572909169017097 1.0
3527000 7967800 4440800 1.2590870428125887
0.0017577721797877375 0.0003909968141029941

In [44]:
df_krx

      Symbol  Market                     Name
0     060310  KOSDAQ                       3S
1     105190   KOSPI                  ACE 200
2     332500   KOSPI                ACE 200TR
3     448870   KOSPI  ACE 23-12 회사채(AA-이상)액티브
4     448880   KOSPI  ACE 24-12 회사채(AA-이상)액티브
...      ...     ...                      ...
7017  437550   KOSPI         히어로즈 글로벌리츠이지스액티브
7018  419890   KOSPI          히어로즈 단기채권ESG액티브
7019  429870   KOSPI            히어로즈 리츠이지스액티브
7020  454780   KOSPI      히어로즈 종합채권(AA-이상)액티브
7021  238490  KOSDAQ                       힘스

[7022 rows x 3 columns]